export const TAGS = [
  { id: 1, name: "Hostel" },
  { id: 2, name: "Club" },
  { id: 3, name: "Academic" },
  { id: 4, name: "Manthan" },
  { id: 5, name: "Spardha" },
  { id: 6, name: "Brahmaputra" },
  { id: 7, name: "Umium" },
  { id: 8, name: "Kameng" },
  { id: 9, name: "Dihing" },
  { id: 10, name: "Dhansiri" },
  { id: 11, name: "Manas" },
  { id: 12, name: "Subhansiri" },
  { id: 13, name: "Siang" },
  { id: 14, name: "Lohit" },
  { id: 15, name: "Kapili" },
  { id: 16, name: "Disang" },
  { id: 17, name: "Dibang" },
  { id: 18, name: "Barak" },
  { id: 19, name: "Cadence" },
  { id: 20, name: "Xpressions" },
  { id: 21, name: "Octaves" },
  { id: 22, name: "Finnese" },
  { id: 23, name: "Montage" },
  { id: 24, name: "Lumiere" },
  { id: 25, name: "LitSoc" },
  { id: 26, name: "DebSoc" },
  { id: 27, name: "CnA" },
  { id: 28, name: "Coding Club" },
  { id: 29, name: "Robotics" },
  { id: 30, name: "E-Cell" },
  { id: 31, name: "Automobiles" },
  { id: 32, name: "Astronomy" },
  { id: 46, name: "IITG.ai" },
  { id: 33, name: "Dance" },
  { id: 34, name: "Drama" },
  { id: 35, name: "Music" },
  { id: 36, name: "Arts" },
  { id: 37, name: "Photography" },
  { id: 38, name: "Moviemaking" },
  { id: 39, name: "Debates" },
  { id: 40, name: "Consulting" },
  { id: 41, name: "Cars" },
  { id: 42, name: "C++" },
  { id: 43, name: "Python" },
  { id: 44, name: "Machine Learning" },
  { id: 45, name: "Java" },
];
