export const TAGS = [
  { id: 1, name: "Hostel" },
  { id: 2, name: "Club" },
  { id: 3, name: "Academic" },
  { id: 4, name: "Manthan" },
  { id: 5, name: "Spardha" },
  { id: 6, name: "Brahmaputra" },
  { id: 7, name: "Umiam" },
  { id: 8, name: "Kameng" },
  { id: 9, name: "Dihing" },
  { id: 10, name: "Dhansiri" },
  { id: 11, name: "Manas" },
  { id: 12, name: "Subhansiri" },
  { id: 13, name: "Siang" },
  { id: 14, name: "Lohit" },
  { id: 15, name: "Kapili" },
  { id: 16, name: "Disang" },
  { id: 17, name: "Dibang" },
  { id: 18, name: "Barak" },
  { id: 19, name: "Cadence" },
  { id: 20, name: "Xpressions" },
  { id: 21, name: "Octaves" },
  { id: 22, name: "Finnese" },
  { id: 23, name: "Montage" },
  { id: 24, name: "Lumiere" },
  { id: 25, name: "LitSoc" },
  { id: 26, name: "DebSoc" },
  { id: 27, name: "CnA" },
  { id: 28, name: "Coding Club" },
  { id: 29, name: "Robotics" },
  { id: 30, name: "E-Cell" },
  { id: 31, name: "Automobiles" },
  { id: 32, name: "Astronomy" },
  { id: 46, name: "IITG.ai" },
  { id: 33, name: "Dance" },
  { id: 34, name: "Drama" },
  { id: 35, name: "Music" },
  { id: 36, name: "Arts" },
  { id: 37, name: "Photography" },
  { id: 38, name: "Moviemaking" },
  { id: 39, name: "Debates" },
  { id: 40, name: "Consulting" },
  { id: 41, name: "Cars" },
  { id: 42, name: "C++" },
  { id: 43, name: "Python" },
  { id: 44, name: "Machine Learning" },
  { id: 45, name: "Java" },
  { id: 46, name: "Chemical" },
  { id: 47, name: "CST" },
  { id: 48, name: "Chemistry" },
  { id: 49, name: "MnC" },
  { id: 50, name: "Mathematics" },
  { id: 51, name: "CSE" },
  { id: 52, name: "Computer Science" },
  { id: 53, name: "Mechanical" },
  { id: 54, name: "Civil" },
  { id: 55, name: "BSBE" },
  { id: 56, name: "BT" },
  { id: 57, name: "Bio Technology" },
  { id: 58, name: "Design" },
  { id: 59, name: "Techniche" },
  { id: 60, name: "Alcheringa" },
  { id: 61, name: "Spirit" },
  { id: 62, name: "Udgam" },
  { id: 63, name: "EP" },
  { id: 64, name: "Engineering Physics" },
  { id: 65, name: "Volleyball" },
  { id: 66, name: "Football" },
  { id: 67, name: "Cricket" },
  { id: 68, name: "Badminton" },
  { id: 69, name: "Table Tennis" },
  { id: 70, name: "Squash" },
  { id: 72, name: "Gym" },
  { id: 73, name: "New Sac" },
  { id: 74, name: "Library" },
  { id: 75, name: "Core 1" },
  { id: 76, name: "Core 2" },
  { id: 77, name: "Core 3" },
  { id: 78, name: "Core 4" },
  { id: 79, name: "Core 5" },
  { id: 80, name: "EEE" },
  { id: 81, name: "ECE" },
  { id: 82, name: "Electical" },
  { id: 83, name: "Old Sac" },
  { id: 84, name: "Food Court" },
  { id: 85, name: "Basketball" },
  { id: 86, name: "Hockey" },
  { id: 87, name: "Athletics" },
  { id: 88, name: "Swimming" },
  { id: 89, name: "Swimming Pool" },
  { id: 90, name: "Kriti" },
  { id: 91, name: "Inter IIT Cult" },
  { id: 92, name: "Inter IIT Sports" },
  { id: 93, name: "Inter IIT Tech" },
  { id: 94, name: "Yoga Room" },
  { id: 95, name: "Aeromodelling Club" },
  { id: 96, name: "CC" },
  { id: 97, name: "CCD" },
  { id: 98, name: "Lecture Hall" },
  { id: 99, name: "Admin Building" },
  { id: 100, name: "Auditorium" },
  { id: 101, name: "Placements" },
  { id: 102, name: "Internship" },
  { id: 103, name: "SWC" },
];
