module.exports.HOSTEL = [
  "Brahmaputra",
  "Umiam",
  "Kameng",
  "Dihing",
  "Dhansiri",
  "Manas",
  "Subhansiri",
  "Siang",
  "Lohit",
  "Kapili",
  "Disang",
  "Dibang",
  "Barak",
];

module.exports.DEPARTMENT = [
  "Chemical",
  "CSE",
  "CST",
  "BSBE",
  "Mechanical",
  "Civil",
  "Mathematics",
  "Design",
  "EEE",
  "ECE",
  "EP",
];

module.exports.CLUB = [
  "Cadence",
  "Xpressions",
  "Octaves",
  "Finnese",
  "Montage",
  "Lumiere",
  "LitSoc",
  "DebSoc",
  "CnA",
  "Coding Club",
  "Robotics",
  "E-Cell",
  "Automobiles",
  "Astronomy",
  "IIG.AI",
];

module.exports.LETTERHEADS = {
  A: "/Images/Letters/large-letter-a.jpg",
  B: "/Images/Letters/large-letter-b.jpg",
  C: "/Images/Letters/large-letter-c.jpg",
  D: "/Images/Letters/large-letter-d.jpg",
  E: "/Images/Letters/large-letter-e.jpg",
  F: "/Images/Letters/large-letter-f.jpg",
  G: "/Images/Letters/large-letter-g.jpg",
  H: "/Images/Letters/large-letter-h.jpg",
  I: "/Images/Letters/large-letter-i.jpg",
  J: "/Images/Letters/large-letter-j.jpg",
  K: "/Images/Letters/large-letter-k.jpg",
  L: "/Images/Letters/large-letter-l.jpg",
  M: "/Images/Letters/large-letter-m.jpg",
  N: "/Images/Letters/large-letter-n.jpg",
  O: "/Images/Letters/large-letter-o.jpg",
  P: "/Images/Letters/large-letter-p.jpg",
  Q: "/Images/Letters/large-letter-q.jpg",
  R: "/Images/Letters/large-letter-r.jpg",
  S: "/Images/Letters/large-letter-s.jpg",
  T: "/Images/Letters/large-letter-t.jpg",
  U: "/Images/Letters/large-letter-u.jpg",
  V: "/Images/Letters/large-letter-v.jpg",
  W: "/Images/Letters/large-letter-w.jpg",
  X: "/Images/Letters/large-letter-x.jpg",
  Y: "/Images/Letters/large-letter-y.jpg",
  Z: "/Images/Letters/large-letter-z.jpg",
};
